export const userMutations = {
  SET_EMAIL: 'SET_EMAIL',
  SET_NAME: 'SET_NAME',
  SET_AVATAR: 'SET_AVATAR'
}

export const twitterMutations = {
  SET_HANDLES: 'SET_HANDLES',
  SET_HANDLE_INFO: 'SET_HANDLE_INFO',
  SET_PROCESSED_DATA: 'SET_PROCESSED_DATA',
  SET_TWEETS: 'SET_TWEETS',
  GET_NETWORK_GRAPH: 'GET_NETWORK_GRAPH'
}
